### ISSUE TITLE
[Repos]: Politespace breaks in build

### ISSUE THREAD

**Issue by JihadMotii-REISys** [GSA/sam-web-design-standards#106]
Hey @joshbruce ,

I'm running into an issue with politespace. Please find the below message that I get on the browser:
`start.js: 13 Uncaught Error: Cannot find module "../../../../node_modules/politespace/src/politespace"`

Even when I run `npm build`, the build does get generated but it throws the following error:
`ERROR in ./~/samwds/src/js/vendor/uswds/start.js`
`Module not found: Error: Can't resolve '../../../../node_modules/politespace/src/politespace' in '/var/www/gsa-iae/apps/REISystems-GSA-CFDA-Angular2-UI/webapp/node_modules/samwds/src/js/vendor/uswds'`
` @ ./~/samwds/src/js/vendor/uswds/start.js 13:18-81`
` @ ./~/samwds/src/js/start.js`
` @ ./src/app/app.module.ts`
` @ ./src/app/index.ts`
` @ ./src/main.ts`
` @ multi main`

I'm using:
- npm 3.10.3
- node v6.4.0
- angular-cli@webpack (for managing Angular2 app)

@diego- @carlosvalle

**Comment by joshbruce** [comment]
@JihadMotii-REISys - Could you verify a couple of things?

Please be sure you are following the instructions in [CONTRIBUTING.md](https://github.com/GSA/sam-web-design-standards/blob/gh-pages-staging/CONTRIBUTING.md) regarding building via Gulp.

Specifically the:

`$ bundle update`

`$ npm update`

**Comment by joshbruce** [comment]
@JihadMotii-REISys - Were you able to resolve this via the instructions provided?

**Comment by JihadMotii-REISys** [comment]
@joshbruce Yes, thank you so much
