### ISSUE TITLE
[Standards]: Font Size/Family recommendations

### ISSUE THREAD

**Issue by jagannathch** [GSA/sam-web-design-standards#127]
## Issue type

Website/UI Components

## What happened

Need recommendations on font size and family. The SAM WDS does not specify one, should we use what's recommended by US WDS? 

https://standards.usa.gov/typography/

## What I expected

Compliance with SAM and/or US WDS

**Comment by jagannathch** [comment]
@joshbruce @nithinemu @tarandhupar @Carryace

**Comment by joshbruce** [comment]
@jagannathch - Hey JC! Thanks for brining this up. A couple of things.

1. We have specified one of the typography pairings from the USWDS: https://gsa.github.io/sam-web-design-standards/getting-started/visual-style/#typography - note: It appears the accordions from the USWDS have been changed and the current HTML pattern used in the SAMWDS does not allow you to expand the typography accordion. See #116 
2. If you believe there's a way to make this more obvious, please submit a pull request or make the suggestion.
3. If you take a look at `/src/stylesheets/core/_variables.scss` you will see the font sizes and faces that get compiled into the final CSS.

**Comment by jagannathch** [comment]
@joshbruce: thanks! your comments above helped. I am closing this now.
