### ISSUE TITLE
[Repos]: Should we copy vendor files...??

### ISSUE THREAD

**Issue by joshbruce** [GSA/sam-web-design-standards#13]
The USWDS uses various node modules: Bourbon, Neat, and so on.

When they compile their code they do not include from the `node_modules` directory; instead, they copy the files from `node_modules` into their `src` files.

1. I'm not sure why this choice was made.
2. It is not the way we are currently doing things.

It's the difference between having `all.scss` look like this:

```
@import 'lib/bourbon';
```

And, what we currently have:

```
@import '../../node_modules/uswds/src/stylesheets/lib/bourbon';
```

I seem to recall @msecret being part of this conversation for the USWDS, maybe he can shed some light.

**Comment by diego-ruiz-rei** [comment]
FYI, we ran into issues with the currently implemented import statements when using npm ver 3.x. Seems that 3.x implements a flat structure when it comes to dependency modules. Can anyone else confirm?

**Comment by joshbruce** [comment]
@diego-ruiz-rei - Think this confirms what you're saying: https://docs.npmjs.com/how-npm-works/npm3

And, I think that answers this question, because the Sass in the last published version went straight to the `node_modules` directory. This repo doesn't - running into issues build the package - per #45. 

Thanks for helping out!

Due to our release schedule I think finishing up on the package build got delayed - apologies - please pardon the bumps as so much is changing. :)

(Admittedly, setting up automated environments isn't quite my wheelhouse yet.)

Would cloning *this* repo and using `src` work for now until we can get the package build sorted?

**Comment by joshbruce** [comment]
ps. Would somebody have time in this Sprint to pair up so I can learn and we can get this fixed? 

I've only seen @tarandhupar setting up an environment, but if someone else is available, I'm not picky. :)

**Comment by joshbruce** [comment]
pps. @diego-ruiz-rei - Given this is new to all of us, I assumed (my fault) this went without saying and, in the future, feel free to post new issues, or questions, or whatnot. :)

**Comment by joshbruce** [comment]
We got it working for now. Thanks to @diego-ruiz-rei, @jagannathch, and @tarandhupar for going down the rabbit-hole on this - actually it's this #45. Would still like to find a more elegant solution, but this will work. 🎩 = /ht
