### ISSUE TITLE
[Actions & Icons]: Deprecate actions and icons?

### ISSUE THREAD

**Issue by joshbruce** [GSA/sam-web-design-standards#14]
## Issue type

* Actions
* Icons

## What happened

Prior to Release 7 various teams were using a mismatching set of actions (links with icons) and icons across the system. In Release 6 we started considering the standardization of icons and actions. Given the new design direction, I'm not sure we actually need these anymore at this time.

Should they be deprecated until actually being defined via the workflow established at the end of Release 6?

**Comment by jagannathch** [comment]
I think we should come up with a list of all the icons being used, standardize and publish onto the UI Kit. Should we have a dictionary of icons that we can build out for future reuse?

**Comment by jagannathch** [comment]
@joshbruce : reference comment above

**Comment by joshbruce** [comment]
@jagannathch - Sorry it took a minute. I got the email from the first and the second, just hadn't been able to get to it. :)

The actions and icons [https://gsa.github.io/sam-web-design-standards/elements/actions-icons/](https://gsa.github.io/sam-web-design-standards/elements/actions-icons/) - sorry I didn't include a link to that page initially - was started for both of the purposes you list.

If you take a look at the [resource component](https://gsa.github.io/sam-web-design-standards/components/resource/) - you will see an example with Action elements.

Right now the pages feel like "under construction" pages though - and we may or may not actually need them. 

Maybe @diego-ruiz-rei and @burgwyn can submit PRs defining the HTML and Sass related to the actions and icons they are currently using to help build this standardization out?
