### ISSUE TITLE
[Website]: Mobile menu not correct

### ISSUE THREAD

**Issue by joshbruce** [GSA/sam-web-design-standards#27]
## Issue type

* Website

## What happened

When making the browser narrow to replicate a mobile experience:

1. The menu icon appears.
2. The menu can be opened and closed.
3. The menu is incorrect - still using the one from the USWDS.

## What I expected

The menu would replicate the desktop experience and function similar to the USWDS.

## Steps to reproduce the issue [optional]

1. Go to site on mobile device (or narrow browser window).
2. Tap/Click "menu".
3. Review navigation links.

## Additional information [optional]

<img width="408" alt="screen shot 2016-08-01 at 8 35 41 am" src="https://cloud.githubusercontent.com/assets/15252830/17294155/f92f6f74-57c2-11e6-9058-161262be7ac6.png">

**Comment by diego-ruiz-rei** [comment]
Just a heads up, I'm noticing that the current USWDS seems to be have their own mobile navigation issues on styles and accordians
