### ISSUE TITLE
[Repos]: Too many SAM Web Design Standards

### ISSUE THREAD

**Issue by joshbruce** [GSA/sam-web-design-standards#30]
## Issue type

* Repos

## What happened

1. In Release 6 we moved the SAM Web Design Standards beta to a repo off of @briangilmangsa.
2. Since Release 4 and 5 an older version has also been available on openIAE (https://github.com/GSA/openIAE and http://gsa.github.io/openIAE/sam_web_standards/).
3. Since Release 3 even older versions could be found on Confluence.
4. Prior to and during Release 3 even older versions were available as PDF documents.

As you can see things have been evolving a lot. Unfortunately, this means there are outdated versions floating around in multiple places.

As of the first couple of days of Release 7 - the SAM Web Design Standards has been moved to the GSA organizational GitHub account. While this may, or may not, be the resting place in perpetuity - it is considered the primary source location.

## What I expected

A primary source location of the SAM Web Design Standards.

- [x] Versions in Confluence are removed - or marked as "archived" in some way and point here.
- [x] Link from openIAE sends users to this location - WF @pammiller0 or @aromero6 to merge PR GSA/openIAE#39.
- [x] Repository under @briangilmangsa is deleted; marked as "archived" in the README with a link here; or, is renamed.
- [x] Update link from Confluence architecture document.

**Comment by joshbruce** [comment]
@jenbesergsa - Testing email rules

**Comment by joshbruce** [comment]
@joshbruce - Should end up in the GitHub folder for J

**Comment by jagannathch** [comment]
bookmarked! 👍

**Comment by joshbruce** [comment]
All cleared out. If you have links to anything other than this GitHub repository. 

Please delete or archive those references.

Thanks!
