### ISSUE TITLE
[Website]: Accordions with code blocks show a gray background

### ISSUE THREAD

**Issue by joshbruce** [GSA/sam-web-design-standards#35]
## Issue type

* Website

## What happened

Was looking at accordions displaying how to use the UI kits and noticed that there is a gray rectangle.

## What I expected

To not see a gray rectangle.

## Steps to reproduce the issue

1. Go to: https://gsa.github.io/sam-web-design-standards/elements/actions-icons/
2. Scroll to JavaScript UI kit usage
3. Expand accordion

## Additional information

<img width="443" alt="screen shot 2016-08-03 at 1 25 04 pm" src="https://cloud.githubusercontent.com/assets/15252830/17375137/c6344268-597d-11e6-9b5c-61f7387cd0d2.png">

**Comment by anuragmundada-reisys** [comment]
@joshbruce The gray rectangle highlights the code in the accordions as below
![screen shot 2016-08-15 at 3 03 30 pm](https://cloud.githubusercontent.com/assets/18703498/17675850/a1c1eb1c-62f9-11e6-9930-45e6bddc4916.png)

the code blocks in the UI kit usage accordions would look something like this if we get rid of the gray rectangle. Is this ok?
![screen shot 2016-08-15 at 2 54 57 pm](https://cloud.githubusercontent.com/assets/18703498/17675634/8ceef56e-62f8-11e6-9c35-a15ac04dbcfc.png)

**Comment by joshbruce** [comment]
@anuragmundada-reisys - Sorry it has taken a moment. For now? Absolutely. 👍 

We are also importing Prism (http://prismjs.com) for syntax highlighting; so, maybe that's another issue...we had it working at one point - not sure when it was lost exactly...been pretty hectic.

Thank you again! I hope things will calm down a bit soon and I can get back in there with y'all.

**Comment by joshbruce** [comment]
A: [ ] prism.js not being included - add `require('./vendor/prismjs/prism.js');` to `/_site-assets/start.js` above `require('./vendor/uswds/start.js');`

B: [ ] `/_site-assets/css/styleguide.scss` modify `code[class*="language-"], pre[class*="language-"]` with `background-color: transparent;`

C (optional): [ ] Create...will get back to you on this one.

A: Before and after

<img width="518" alt="screen shot 2016-08-19 at 12 22 42 pm" src="https://cloud.githubusercontent.com/assets/15252830/17816555/b3e2c7b0-6607-11e6-9e1f-3868c108e6ca.png">

<img width="489" alt="screen shot 2016-08-19 at 12 22 55 pm" src="https://cloud.githubusercontent.com/assets/15252830/17816557/b5ee4c64-6607-11e6-8b58-aff3083b65da.png">

B: Before and after

<img width="496" alt="screen shot 2016-08-19 at 12 27 36 pm" src="https://cloud.githubusercontent.com/assets/15252830/17816661/5b7f155a-6608-11e6-9e33-b0e5e9e53e71.png">

<img width="403" alt="screen shot 2016-08-19 at 12 27 23 pm" src="https://cloud.githubusercontent.com/assets/15252830/17816664/5fd83744-6608-11e6-851b-0342598aa27b.png">

**Comment by joshbruce** [comment]
Closed via #82
