### ISSUE TITLE
[Repos]: Too many GitHub notifications! Wiki page...??

### ISSUE THREAD

**Issue by joshbruce** [GSA/sam-web-design-standards#36]
## Issue type

* The GitHub repositories will be sending out a lot of notifications as they are leveraged more.

## What happened

My inbox is overflowing! I want to keep up, but these notifications are not as important as others.

## Proposed solution

Would it be helpful to create a Wiki page that describes how to setup email rules in Outlook, Apple Mail, and Gmail (filters)?

In this setup, what would happen for general notifications:

1. The email client would see the email.
2. Apply the rules.
3. Move the email to a separate folder (@GitHub, for example) - still marked as unread.

Note: A rule can be applied (at least for Outlook and Apple Mail) that will keep notifications where your name is mentioned in your inbox. So:

1. The email client would see the email.
2. Check for @joshbruce.
3. Apply the rules.
4. And leave the email in my inbox - because that one is at least specifically to me.

**Comment by piercept17** [comment]
Yes, please set up a page!  I'm on email overload.

**Comment by joshbruce** [comment]
@piercept17 - See https://github.com/GSA/sam-web-design-standards/wiki/Mail-Handling-MacOS

Let me know what steps could have been helped with images or screenshots.
