### ISSUE TITLE
[Website]: Code examples and samples require JavaScript

### ISSUE THREAD

**Issue by joshbruce** [GSA/sam-web-design-standards#37]
## Issue type

This is a duplication of the one from the UWDS: 18f/web-design-standards#1305

## What happened

The code samples are generated after page load. There is a JS function that checks for a `div` with class `preview`. It copies the contents, inserts them into a string. Then adds the element to the page.

Therefore, if JS fails or is disabled the code sample boxes don't show up. See the 18f ticket.

## What I expected

Code samples would *always* be displayed. We can make this part of the Jekyll build - see the solution for the USWDS. It would change the file structure a bit, and make defining a component a little more interesting.

## Steps to reproduce the issue [optional]

1. Go to: https://gsa.github.io/sam-web-design-standards/elements/actions-icons/
2. Notice the code accordion.
3. Disable JavaScript in your browser.
3. Refresh the page
4. Notice the code accordion is missing.

ps. I wasn't sure if this would be a level 1 or 2 defect as they both apply; however, the dependency on JavaScript means it match our definition of done.

**Comment by joshbruce** [comment]
#66

**Comment by joshbruce** [comment]
Created a `/code/main.html` include to make the building of content more generic.

Created a `/code/template-code.html` to be used a baseline when converting elements and components (copy/paste into new file).

- [x] Accordions
- [x] Alerts
- [x] Footers
- [x] Header
- [x] Side navigation
- [ ] Pagination
- [ ] Name form
- [ ] Address form
- [ ] Sign-in form
- [ ] Registration form
- [ ] Inline feedback form (quick)
- [ ] Support form
- [ ] Search bar
- [ ] Search result
- [ ] Actions & icons
- [ ] Buttons
- [ ] Text inputs and area
- [ ] Select
- [ ] Date input
- [ ] Links
- [ ] Lists
- [ ] Labels
- [ ] Tables

**Comment by anuragmundada-reisys** [comment]
@joshbruce I have covered till inlinefeedbackform_quick! Will commit shortly!

**Comment by joshbruce** [comment]
@anuragmundada-reisys - Sweet! That is so awesome. Thank you so much. I'm going to remove the JS file on my next one.

I love when meetings get cancelled. 👍

**Comment by joshbruce** [comment]
@diego-ruiz-rei & @anuragmundada-reisys - Merged and site updated for end of Sprint demo. Think this could totally be something you demo. Thanks again!
