### ISSUE TITLE
[Standards]: Placeholder attribute in Text Control

### ISSUE THREAD

**Issue by ChristyHermansen** [GSA/sam-web-design-standards#48]
[

## Question

Are we using the placeholder element for text controls?  Are there accessibility issues with it?

## Additional information [optional]

* See attached image

**Comment by jagannathch** [comment]
@ChristyHermansen : I think we should consider using placeholder texts. From an accessibility standpoint, we should consider moving the placeholder text to a label (which we should use anyway for screen readers) and upon "focus" call out the label. Here is an example implementation which uses JQuery:http://www.maxability.co.in/demos/placeholder.html#solution1

@joshbruce @tarandhupar : thoughts?

**Comment by joshbruce** [comment]
@ChristyHermansen, @jagannathch, @tarandhupar - I agree with JC.

http://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#the-placeholder-attribute

> A hint could be a sample value or a brief description of the expected format.

What I interpret this to mean is that it is *not* meant to be a replacement of the `label`, but a demonstration.

So:

Label: First name
Placeholder: John

**Comment by joshbruce** [comment]
ps. Dreamhost uses an approach similar to the one JC referenced. We could use the `usa-sr-only` class to hide the label. Then use jQuery - or some other library to use a CSS3 transition via a class change when the element gains focus. 

This would still use the same initial HTML pattern from the standards - and placeholder text should disappear on focus anyway.

https://panel.dreamhost.com

The major con to using the `usa-sr-only` piece is that we lose the label - even if JS fails. So, maybe only apply it if JS succeeds after page load...?

**Comment by jagannathch** [comment]
@joshbruce what about using the "<noscript>" tag in the HTML in the event that JS is disabled?

**Comment by jagannathch** [comment]
BTW -- side note: https://github.com/18F/web-design-standards/issues/883

**Comment by joshbruce** [comment]
@jagannathch - Markdown gets a little funny with code. if you surround the text with \` - it turns into `<code>Hello</hello>`. If you use three ticks, it turns into `<code><pre>Hello</pre></code>`.

It's the difference between Progressive Enhancement and Graceful Degradation. It's not that `<noscript>` = Graceful Degradation - it depends on how the approach to `<noscript>` is implemented. See references below.

https://gsa.github.io/sam-web-design-standards/getting-started/developers/#fn:w3cProgressiveEnhancement

https://www.w3.org/wiki/Graceful_degradation_versus_progressive_enhancement

**Comment by joshbruce** [comment]
I think there is also something to be said regarding visibility and permanence.

The `placeholder` attribute is only visible when the text field is empty. To @jenbesergsa's point, via email, having the label above the text field means it's always on screen; so, users can quickly scan to find the field they are looking for.

Personally, I've always had a soft-spot for putting the label to the side of the input field - if I'm trying relentlessly to conserve vertical space. And I think, for now, sticking with the label above per the Standards is a good place to start.

**Comment by ChristyHermansen** [comment]
From an email by @jenbesergsa 

I researched placeholder text within input fields and came to a conclusion that for large forms - we should use labels outside of the input fields. Users can forget what the field was for after filling out a large form and reviewing the form to make any last minute changes. 
Reference:
WEB FORM DESIGN

by LUKE WROBLEWSKI

**Comment by jagannathch** [comment]
@ChristyHermansen 👍  agreed...and the US web design standards augment that as well. 

https://standards.usa.gov/form-templates/
