### ISSUE TITLE
Secondary Navigation not linking to sub-heading

### ISSUE THREAD

**Issue by BrianGilmanGSA** [GSA/sam-web-design-standards#60]
## Issue type

*What kind of issue are you working on?*

* Website

## What happened

When secondary navigation is selected on the SWDS components page the page does not jump to that sub heading even though the URL changes. 

## What I expected

As the secondary navigation link is selected the sub heading that is selected should be then moved to on the page. 

## Additional information [optional]

![nav issue](https://cloud.githubusercontent.com/assets/15361800/17707030/79e05a80-63ac-11e6-8020-0ff7d54e50e9.png)

**Comment by joshbruce** [comment]
See also #57

**Comment by BrianGilmanGSA** [comment]
@joshbruce @anuragmundada-reisys Looks like the 2nd nav anchors in the element's, component's  and page template's pages are not scrolling correctly.

**Comment by anuragmundada-reisys** [comment]
@joshbruce I don't see the changes I made in the browser when I inspect the page. I'm not sure if this is an issue with the build?
You can see the changes I made on Github https://github.com/GSA/sam-web-design-standards/blob/gh-pages-staging/_includes/elements/select.html
![screen shot 2016-08-17 at 10 31 53 am](https://cloud.githubusercontent.com/assets/18703498/17740230/dd9d8458-6465-11e6-8c50-3171bb1c9dfe.png)

whereas, when I inspect the element in the browser, I don't see that change
![screen shot 2016-08-17 at 10 29 52 am](https://cloud.githubusercontent.com/assets/18703498/17740162/9f6c58b2-6465-11e6-8725-2dd867b18e97.png)

**Comment by joshbruce** [comment]
@anuragmundada-reisys - I will be tagging this as a request for #12.

Right now we submit our pull requests to `gh-pages-staging` - this does not do a Jekyll build.

When we merge `gh-pages-staging` into `gh-pages` GitHub will perform a Jekyll build via GitHub Pages. In the future, what we would like to setup is something where the SAM.gov platform will actually pull from both branches and perform independent Jekyll builds to be able to display both the `staging` and the `live` sites.

Hope that helps.

**Comment by anuragmundada-reisys** [comment]
@joshbruce Yes that would be pretty helpful. Thank you!
