### ISSUE TITLE
[Header + Footer]: Refactor & re-engineer header and footer

### ISSUE THREAD

**Issue by joshbruce** [GSA/sam-web-design-standards#68]
## Issue type

* Package

## What happened

Added the footer code from #47 to the Footers section of the Navigation page. Appears the GSA logo was missed during code review (sorry about that). It appears we only have PNGs.

## What I expected

To see the GSA logo in the SAM Footer. To have the GSA logo in `/src/img`.

Would it be possible to get both a PNG and SVG equivalent of both the transition.SAM.gov and GSA logos? (Needed for package - at least the GSA logo.)

Then display them via CSS (with fallback - see `buttons` -> `usa-dismiss-button`)? (Nice to have, but would require some reengineering.)

Tagging in: @burgwyn and @eoladipo

**Comment by burgwyn** [comment]
@joshbruce - can we get a corresponding Jira ticket?

**Comment by joshbruce** [comment]
@burgwyn - Will see what we can do.

Tagging: @ChristyHermansen and @BrianGilmanGSA

**Comment by joshbruce** [comment]
ps. @burgwyn - If you email them to me, I should be able to do it, if that's a relatively easy lift.

**Comment by joshbruce** [comment]
#71 - Updates the references to the images.

Nice to have:

- [ ] Make `a` display-block
- [ ] Add `background-image` to `header.scss` and `footer.scss`
- [ ] Should include fallback from SVG to PNG - see `/src/stylesheets/elements/buttons` -> `usa-dismiss-button`

**Comment by joshbruce** [comment]
ps. Per the prioritization guidelines:

lvl1
lvl2
r&r - you are here. :)
nf

This is not a high priority at this time.

**Comment by joshbruce** [comment]
I submitted PR #122 to re-engineer the header and footer...ready for review.

Below are screenshots of the results as seen on the Microsite for both mobile and desktop. Until we get #83 - implemented or determine #83 cannot be done - this can help in the review process.

Note: Reviews done this way will not include a code review of the HTML itself, which is highly recommended and beneficial to our technical goals related to semantic markup and accessibility.

<img width="502" alt="screen shot 2016-09-12 at 11 31 42 am" src="https://cloud.githubusercontent.com/assets/15252830/18441901/ad7fe1a4-78dc-11e6-9ade-eb085ff757c9.png">

<img width="1009" alt="screen shot 2016-09-12 at 11 31 59 am" src="https://cloud.githubusercontent.com/assets/15252830/18441904/af2daffe-78dc-11e6-913a-349b8148f2bf.png">
