### ISSUE TITLE
[Header + website]: Duplicate max width style in samwds css

### ISSUE THREAD

**Issue by eoladipo** [GSA/sam-web-design-standards#95]
## What happened

There's a duplicate max-width style for the usa-grid, usa-grid-full styles in the samwds css. The last max-width style overwrites the first.

## What I expected
Only one max-width style on the usa-grid, usa-grid-full to match the 1040px uswds style. The wider width 1200px should be a separate samwds style

## Additional information 

In looking at the files here's where I see the style been set:
sam-web-design-standards/src/stylesheets/lib/lib/settings/_grid.scss - has a max-width variable

sam-web-design-standards/src/stylesheets/lib/lib/grid/_outer-container.scss - max-width variable used here in the max-width declaration in the mixin

sam-web-design-standards/src/stylesheets/lib/core/_grid.scss - uses the outer container mixin which includes the first max-width style that gets overwritten by the second max-width declaration in the same file

I know for the SAM header and footer, the larger max-width is what needs to be used but I believe it needs to be set outside the uswds styles. 

@joshbruce Let me know if we need any further discussion on this it'll be good to come to a resolution sooner rather later, thanks.

**Comment by joshbruce** [comment]
@eoladipo - Hey! Thanks for posting the issue. May need to wait until tomorrow to do a call. 

What specific css class is affected by this outcome? If I'm picking up what you're saying, it would be the `.usa-grid` and `.usa-grid-full`.

If we look at `/src/stylesheets/core/_variables.scss` there is the `$site-max-width` value - this value is what sets the `.usa-grid` and `.usa-grid-full` max-widths. Do me a favor and set that to the desired width of the header (sounds like 1200px).

We have been considering making the max-width for the site wider, and this should be in keeping with that.

**Comment by eoladipo** [comment]
@joshbruce Yes it's the .usa-grid and the .usa-grid-full styles. The $site-max-width is currently set to 1040px and updating it is no problem, however the duplicate $max-width that is coming from the files mentioned above will still exist if they're not updated.

**Comment by joshbruce** [comment]
@eoladipo - Thanks! Looked into a little further. Opened #96. Will close this one for now, because it appears there could be a higher-level issue and solution to be had...maybe?
